# Generated by Django 3.2.7 on 2022-05-04 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Chairman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.IntegerField(blank=True, null=True, unique=True)),
                ('status', models.CharField(default=' ', max_length=10)),
                ('details', models.CharField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=11)),
                ('occupation', models.CharField(max_length=50)),
                ('job_address', models.TextField(max_length=500)),
                ('birthdate', models.DateField(blank=True, max_length=20, null=True)),
                ('marital_status', models.CharField(max_length=20)),
                ('no_of_members', models.CharField(max_length=20)),
                ('native', models.CharField(max_length=100)),
                ('nationality', models.CharField(default='Indian', max_length=100)),
                ('no_of_vehicles', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('id_proof', models.FileField(default='media/default.png', upload_to='media/images')),
                ('profile_pic', models.FileField(default='media/default.png', upload_to='media/images')),
                ('house_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='House', to='Member.house')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Member', to='Chairman.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pic', models.FileField(blank=True, null=True, upload_to='media/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/videos/')),
            ],
        ),
        migrations.CreateModel(
            name='NoticeView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Member.member')),
                ('notice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Member.notice')),
            ],
        ),
    ]
