# Generated by Django 3.2.7 on 2022-05-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='pic',
            field=models.FileField(null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='video',
            field=models.FileField(null=True, upload_to='media/videos/'),
        ),
    ]
